### ISSUE TITLE
Can not use option --google | TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ghost** [j3ers3/Searpy#1]
Hello, first of all i really thankful for your awesome and powerful tools. The installation is good so far for the config file also good and i just add the shodan api to it, for the google proxy i am not sure so i leave it default:

proxy = {
    'http':'http://127.0.0.1:8001',
    'https':'http://127.0.0.1:8001'
}

after save all the config than i ran:
=> python Searpy.py --shodan -s "Webcam" -l 30 
it showing the result normally

but when i ran this --google option it showing like this:
=> python Searpy.py --google -s "inurl:php?id=" -p 3 

#result
Traceback (most recent call last):
  File "Searpy.py", line 133, in <module>
    for i in s.result:
TypeError: 'NoneType' object is not iterable

So what could i do?

note: i ran in my host machine kali-linux 2019.4

**Comment by j3ers3** [comment]
hi, if you don't need proxy 😃

```
proxy = {
}
```

**Comment by ghost** [comment]
ohhh i seeee, thank you.

**Comment by ghost** [comment]
Hi, after remove those things, i still get the same error.

[+] config file
[https://cdn-35.anonfile.com/NdOeT9Han6/9ce996c5-1577155662/2019-12-24_093442.png](url)

[+] error
[https://cdn-33.anonfile.com/PbOeTfHcn0/1cf9e645-1577155654/2019-12-24_093550.png](url)

**Comment by j3ers3** [comment]
This may be caused by the bs4 module，try `pip install soupsieve`, or google it

**Comment by ghost** [comment]
Okay now i manage to solved it by reinstall the pip2 and the bs4 packages. :)
