### ISSUE TITLE
In Python3 about shodan

### ISSUE THREAD

**Issue by Startr4ck** [j3ers3/Searpy#2]
In Your shodan_module，with Python3 
  You cannot use base64 to encode requests.content cause .content is type of bytes，also python3 cannot use .encode()

**Comment by Startr4ck** [comment]
I done this by multi errors 

> import requests
import base64
import mmh3
response = requests.get('https://www.pronhub.com/favicon.ico')
data = base64.encodebytes(response.content)
print(str(data,encoding='utf-8'))


hash = mmh3.hash(str(data,encoding='utf-8'))
print (hash)

**Comment by j3ers3** [comment]
thanks, fix @Startr4ck
