### ISSUE TITLE
Fofa.__init__() missing 1 required positional argument: 'proxy'

### ISSUE THREAD

**Issue by yz1639** [j3ers3/Searpy#6]
## 调用fofa类，缺少proxy实参

![image](https://user-images.githubusercontent.com/44149984/189287294-469b28f2-e0cf-4dc4-9cf2-a8025be10380.png)

![image](https://user-images.githubusercontent.com/44149984/189286989-8cccb4e0-03bb-4abd-98ce-b55650b045b0.png)

![image](https://user-images.githubusercontent.com/44149984/189286747-d443dddb-c7fe-4f4a-b516-000fefb467f9.png)

## 其他类都带了的，应该是忘了加吧

![image](https://user-images.githubusercontent.com/44149984/189287147-881b4884-3ca6-4d0f-ae56-2ffd71d30afc.png)

![image](https://user-images.githubusercontent.com/44149984/189287908-6bbbe595-d819-49eb-bbb4-cffc09c1ca95.png)

**Comment by j3ers3** [comment]
get
